Repository therealmonE/fire-res, pull requests merged in 2020-11, with the labels that each got.

#12 Added double point / model refactoring
  core/src/main/java/io/github/therealmone/fireres/core/config/InterpolationPoints.java
  core/src/main/java/io/github/therealmone/fireres/core/config/SampleProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/factory/PointSequenceFactory.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/MultiplePointSequencesGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/PointSequenceGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/FurnaceTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/MaxAllowedTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/MinAllowedTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/StandardTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/ThermocoupleMeanGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/ThermocouplesTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/model/FurnaceTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/MaxAllowedTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/MinAllowedTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/Point.java
  core/src/main/java/io/github/therealmone/fireres/core/model/PointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/model/Sample.java
  core/src/main/java/io/github/therealmone/fireres/core/model/SmoothedPointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/model/StandardTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/ThermocoupleMeanTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/ThermocoupleTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/FurnaceTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/MaxAllowedTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/MinAllowedTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/StandardTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/ThermocoupleMeanTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/ThermocoupleTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/point/DoublePoint.java
  core/src/main/java/io/github/therealmone/fireres/core/model/point/IntegerPoint.java
  core/src/main/java/io/github/therealmone/fireres/core/model/point/Point.java
  core/src/main/java/io/github/therealmone/fireres/core/model/point/TemperaturePoint.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/PointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/SmoothedTemperaturePointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/TemperaturePointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/report/Report.java
  core/src/main/java/io/github/therealmone/fireres/core/report/ReportBuilder.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/FunctionUtils.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/InterpolationUtils.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/MathUtils.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/ValidationUtils.java
  core/src/test/java/io/github/therealmone/fireres/core/TestUtils.java
  core/src/test/java/io/github/therealmone/fireres/core/model/point/DoublePointTest.java
  core/src/test/java/io/github/therealmone/fireres/core/utils/InterpolationUtilsTest.java
  excel/src/main/java/io/github/therealmone/fireres/excel/ExcelReportConstructor.java
  excel/src/main/java/io/github/therealmone/fireres/excel/model/Column.java
  excel/src/main/java/io/github/therealmone/fireres/excel/model/FurnaceTemperatureColumn.java
  excel/src/main/java/io/github/therealmone/fireres/excel/model/MaxAllowedTemperatureColumn.java
  excel/src/main/java/io/github/therealmone/fireres/excel/model/MinAllowedTemperatureColumn.java
  excel/src/main/java/io/github/therealmone/fireres/excel/model/PointSequenceColumn.java
  excel/src/main/java/io/github/therealmone/fireres/excel/model/StandardTemperatureColumn.java
  excel/src/main/java/io/github/therealmone/fireres/excel/model/ThermocoupleTemperatureColumn.java
  excel/src/main/java/io/github/therealmone/fireres/excel/model/ThermocouplesMeanTemperatureColumn.java
  excel/src/test/java/io/github/therealmone/fireres/excel/ExcelReportConstructorTest.java
Labels: code improvement

#13 Prepared mean function generator for reuse
  core/src/main/java/io/github/therealmone/fireres/core/config/InterpolationPoints.java
  core/src/main/java/io/github/therealmone/fireres/core/config/SampleProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/exception/InvalidMeanFunctionException.java
  core/src/main/java/io/github/therealmone/fireres/core/exception/InvalidMeanTemperatureException.java
  core/src/main/java/io/github/therealmone/fireres/core/exception/MeanChildFunctionGenerationException.java
  core/src/main/java/io/github/therealmone/fireres/core/exception/ThermocouplesTemperatureGenerationException.java
  core/src/main/java/io/github/therealmone/fireres/core/factory/PointSequenceFactory.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/MultiplePointSequencesGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/PointSequenceGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/common/MeanChildFunctionsGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/common/MeanFunctionGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/FurnaceTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/MaxAllowedTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/MinAllowedTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/StandardTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/ThermocouplesTempGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/FurnaceTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/MaxAllowedTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/MinAllowedTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/StandardTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/ThermocoupleMeanTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/firemode/ThermocoupleTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/model/point/TemperaturePoint.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/IntegerPointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/PointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/SmoothedIntegerPointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/SmoothedTemperaturePointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/TemperaturePointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/report/ReportBuilder.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/FunctionUtils.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/InterpolationUtils.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/MathUtils.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/ValidationUtils.java
  core/src/test/java/io/github/therealmone/fireres/core/TestUtils.java
  core/src/test/java/io/github/therealmone/fireres/core/utils/InterpolationUtilsTest.java
  excel/src/test/java/io/github/therealmone/fireres/excel/ExcelReportConstructorTest.java
Labels: code improvement

#15 Support default values in config
  application.conf
  cli/pom.xml
  cli/src/test/java/io/github/therealmone/fireres/cli/ApplicationTest.java
  cli/src/test/resources/minimum.conf
  core/pom.xml
  core/src/main/java/io/github/therealmone/fireres/core/config/RandomPointsProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/config/SampleProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/config/TemperatureProperties.java
Labels: code improvement

#14 генерация точек для графика избыточного давления
  application.conf
  cli/src/test/resources/minimum.conf
  core/src/main/java/io/github/therealmone/fireres/core/config/GenerationProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/config/PressureProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/factory/PointSequenceFactory.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/impl/ExcessPressureGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/model/pressure/SamplePressure.java
  core/src/main/java/io/github/therealmone/fireres/core/model/sequence/DoublePointSequence.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/MathUtils.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/RandomUtils.java
  core/src/test/java/io/github/therealmone/fireres/core/TestUtils.java
  core/src/test/java/io/github/therealmone/fireres/core/generator/impl/ExcessPressureGeneratorTest.java
Labels: enhancement

#28 Added unheated surface report generator
  core/src/main/java/io/github/therealmone/fireres/core/common/report/FullReport.java
  core/src/main/java/io/github/therealmone/fireres/core/common/report/FullReportBuilder.java
  core/src/main/java/io/github/therealmone/fireres/core/exception/ValidationException.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/UnheatedSurfaceFactory.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/config/UnheatedSurfaceGroupProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/config/UnheatedSurfaceProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/config/UnheatedSurfaceSecondaryGroupProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/generator/UnheatedSurfaceMeanBoundGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/generator/UnheatedSurfaceThermocoupleBoundGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/model/UnheatedSurfaceGroup.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/model/UnheatedSurfaceMeanBound.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/model/UnheatedSurfaceMeanTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/model/UnheatedSurfaceSample.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/model/UnheatedSurfaceThermocoupleBound.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/model/UnheatedSurfaceThermocoupleTemperature.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/report/UnheatedSurfaceReport.java
  core/src/main/java/io/github/therealmone/fireres/core/unheated/report/UnheatedSurfaceReportBuilder.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/FunctionUtils.java
  core/src/main/java/io/github/therealmone/fireres/core/utils/InterpolationUtils.java
  core/src/test/java/io/github/therealmone/fireres/core/TestGenerationProperties.java
  core/src/test/java/io/github/therealmone/fireres/core/TestUtils.java
  core/src/test/java/io/github/therealmone/fireres/core/common/report/FullReportBuilderTest.java
  core/src/test/java/io/github/therealmone/fireres/core/firemode/FireModeFactoryTest.java
  core/src/test/java/io/github/therealmone/fireres/core/pressure/ExcessPressureFactoryTest.java
  core/src/test/java/io/github/therealmone/fireres/core/unheated/UnheatedSurfaceFactoryTest.java
  excel/src/test/java/io/github/therealmone/fireres/excel/ExcelReportConstructorTest.java
Labels: enhancement

#30 Specify filename in config
  application.conf
  cli/src/main/java/io/github/therealmone/fireres/cli/Application.java
  cli/src/main/java/io/github/therealmone/fireres/cli/ProgramArguments.java
  cli/src/test/java/io/github/therealmone/fireres/cli/ApplicationTest.java
  cli/src/test/resources/minimum.conf
  core/src/main/java/io/github/therealmone/fireres/core/common/config/GeneralProperties.java
  run-cli.sh
Labels: enhancement

#36 Allow to choose reports
  application.conf
  cli/src/test/resources/maximum.conf
  cli/src/test/resources/minimum.conf
  core/src/main/java/io/github/therealmone/fireres/core/config/GeneralProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/config/ReportType.java
  core/src/main/java/io/github/therealmone/fireres/core/config/SampleProperties.java
  excel-report.xlsx
  excel/src/main/java/io/github/therealmone/fireres/excel/ExcelModule.java
  excel/src/main/java/io/github/therealmone/fireres/excel/ExcelReportConstructor.java
  excel/src/test/java/io/github/therealmone/fireres/excel/TestGenerationProperties.java
Labels: enhancement

#37 add heat flow graph
  excess-pressure/src/main/java/io/github/therealmone/fireres/excess/pressure/ExcessPressureModule.java
  fire-mode/pom.xml
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/FireModeModule.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/factory/FireModeFactory.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/generator/FurnaceTempGenerator.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/generator/MaxAllowedTempGenerator.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/generator/MinAllowedTempGenerator.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/generator/StandardTempGenerator.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/model/FireModeSample.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/model/FurnaceTemperature.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/model/MaxAllowedTemperature.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/model/MinAllowedTemperature.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/model/StandardTemperature.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/model/ThermocoupleMeanTemperature.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/model/ThermocoupleTemperature.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/report/FireModeReport.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/report/FireModeReportProvider.java
  fire-mode/src/test/java/io/github/therealmone/fireres/firemode/GuiceRunner.java
  fire-mode/src/test/java/io/github/therealmone/fireres/firemode/TestGenerationProperties.java
  fire-mode/src/test/java/io/github/therealmone/fireres/firemode/TestUtils.java
  fire-mode/src/test/java/io/github/therealmone/fireres/firemode/report/FireModeReportRepeatingTest.java
  fire-mode/src/test/java/io/github/therealmone/fireres/firemode/report/FireModeReportTest.java
  heat-flow/pom.xml
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/HeatFlowModule.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/factory/HeatFlowFactory.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/model/HeatFlowBound.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/model/HeatFlowMeanTemperature.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/model/HeatFlowSample.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/model/HeatFlowSensorTemperature.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/report/HeatFlowReport.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/report/HeatFlowReportProvider.java
  heat-flow/src/test/java/io/github/therealmone/fireres/heatflow/GuiceRunner.java
  heat-flow/src/test/java/io/github/therealmone/fireres/heatflow/TestGenerationProperties.java
  heat-flow/src/test/java/io/github/therealmone/fireres/heatflow/TestUtils.java
  heat-flow/src/test/java/io/github/therealmone/fireres/heatflow/report/HeatFlowReportRepeatingTest.java
  heat-flow/src/test/java/io/github/therealmone/fireres/heatflow/report/HeatFlowReportTest.java
  pom.xml
  unheated-surface/src/main/java/io/github/therealmone/fireres/unheated/surface/UnheatedSurfaceModule.java
Labels: enhancement

#38 Generate excess pressure using noise
  application.conf
  cli/src/test/resources/maximum.conf
  core/pom.xml
  core/src/main/java/io/github/therealmone/fireres/core/CoreModule.java
  core/src/main/java/io/github/therealmone/fireres/core/config/excess/pressure/ExcessPressureProperties.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/Noise.java
  core/src/main/java/io/github/therealmone/fireres/core/model/DoublePoint.java
  core/src/main/java/io/github/therealmone/fireres/core/model/IntegerPoint.java
  core/src/main/java/io/github/therealmone/fireres/core/model/Point.java
  core/src/main/java/io/github/therealmone/fireres/core/model/PointSequence.java
  core/src/test/java/io/github/therealmone/fireres/core/model/DoublePointTest.java
  excel/src/main/java/io/github/therealmone/fireres/excel/column/excess/pressure/DeltaColumn.java
  excel/src/main/java/io/github/therealmone/fireres/excel/column/excess/pressure/PressureColumn.java
  excess-pressure/src/main/java/io/github/therealmone/fireres/excess/pressure/factory/ExcessPressureFactory.java
  excess-pressure/src/main/java/io/github/therealmone/fireres/excess/pressure/generator/ExcessPressureGenerator.java
  excess-pressure/src/test/java/io/github/therealmone/fireres/excess/pressure/TestGenerationProperties.java
  pom.xml
Labels: code improvement, enhancement

#45 Added interval / dispersion coefficient to interpolation
  application.conf
  cli/src/test/resources/maximum.conf
  core/src/main/java/io/github/therealmone/fireres/core/config/Interpolation.java
  core/src/main/java/io/github/therealmone/fireres/core/config/InterpolationPoint.java
  core/src/main/java/io/github/therealmone/fireres/core/config/Interval.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/MeanFunctionGenerator.java
  excel/src/test/java/io/github/therealmone/fireres/excel/TestGenerationProperties.java
Labels: enhancement
