Repository therealmonE/fire-res, pull requests merged in 2020-12, with the labels that each got.

#47 Fire mode generator strategy fix
  core/src/main/java/io/github/therealmone/fireres/core/generator/strategy/BackwardChildFunctionGeneratorStrategy.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/strategy/ForwardChildFunctionGeneratorStrategy.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/generator/FireModeGeneratorStrategy.java
  fire-mode/src/main/java/io/github/therealmone/fireres/firemode/report/FireModeReportProvider.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/factory/HeatFlowChildFunctionGeneratorStrategy.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/factory/HeatFlowFactory.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/generator/HeatFlowGeneratorStrategy.java
  unheated-surface/src/main/java/io/github/therealmone/fireres/unheated/surface/factory/UnheatedSurfaceFactory.java
  unheated-surface/src/main/java/io/github/therealmone/fireres/unheated/surface/generator/UnheatedSurfaceGeneratorStrategy.java
Labels: bug

#49 Bugfix/fireres-46
  application.conf
  cli/src/test/resources/maximum.conf
  core/src/main/java/io/github/therealmone/fireres/core/config/Interpolation.java
  core/src/main/java/io/github/therealmone/fireres/core/factory/MeanFunctionFactory.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/MeanChildFunctionsGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/MeanFunctionGenerator.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/strategy/BackwardChildFunctionGeneratorStrategy.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/strategy/ChildFunctionGeneratorStrategy.java
  core/src/main/java/io/github/therealmone/fireres/core/generator/strategy/ForwardChildFunctionGeneratorStrategy.java
  excel/src/test/java/io/github/therealmone/fireres/excel/GuiceRunner.java
  excel/src/test/java/io/github/therealmone/fireres/excel/TestGenerationProperties.java
  fire-mode/src/test/java/io/github/therealmone/fireres/firemode/TestGenerationProperties.java
  heat-flow/src/main/java/io/github/therealmone/fireres/heatflow/generator/HeatFlowGeneratorStrategy.java
  unheated-surface/src/main/java/io/github/therealmone/fireres/unheated/surface/generator/UnheatedSurfaceGeneratorStrategy.java
  unheated-surface/src/test/java/io/github/therealmone/fireres/unheated/surface/report/UnheatedSurfaceReportTest.java
Labels: bug

#51 Removed poorly visible colors
  excel/src/main/java/io/github/therealmone/fireres/excel/style/chart/AvailableColors.java
  excel/src/main/java/io/github/therealmone/fireres/excel/style/chart/DefaultDataLineProperties.java
Labels: bug

#48 Changed sheets names
  excel/src/main/java/io/github/therealmone/fireres/excel/sheet/HeatFlowSheetsProvider.java
  excel/src/main/java/io/github/therealmone/fireres/excel/sheet/UnheatedSurfaceSheetsProvider.java
Labels: enhancement

#58 Img
  docs/images/wiki/UnheatedSurface-11.png
  docs/images/wiki/UnheatedSurface-12.png
  docs/images/wiki/UnheatedSurface-13.png
  docs/images/wiki/UnheatedSurface-21.png
  docs/images/wiki/UnheatedSurface-22.png
  docs/images/wiki/UnheatedSurface-23.png
  docs/images/wiki/heat-flow-01.png
  docs/images/wiki/heat-flow-02.png
  docs/images/wiki/heat-flow-03.png
Labels: documentation
